---
- name: "Create Dashy namespace"
  kubernetes.core.k8s:
    name: "{{ dashy_namespace }}"
    api_version: "v1"
    kind: "Namespace"
    state: "present"

- name: "Create Helm CRD for Dashy"
  kubernetes.core.k8s:
    template: "helm.j2"
    state: "present"
