---
- name: "Create Keycloak namespace"
  kubernetes.core.k8s:
    name: "{{ keycloak_namespace }}"
    api_version: "v1"
    kind: "Namespace"
    state: "present"

- name: "Create secret for Keycloak"
  kubernetes.core.k8s:
    template: "secret.j2"
    state: "present"

- name: "Create Database CRD for Keycloak"
  kubernetes.core.k8s:
    template: "database.j2"
    state: "present"

- name: "Create Helm CRD for Keycloak"
  kubernetes.core.k8s:
    template: "helm.j2"
    state: "present"
