---
- name: "Create home realm"
  community.general.keycloak_realm:
    auth_keycloak_url: "{{ keycloak_auth_url }}"
    auth_realm: "master"
    auth_username: "{{ keycloak_admin_name }}"
    auth_password: "{{ keycloak_admin_password }}"
    id: "{{ keycloak_realm }}"
    realm: "{{ keycloak_realm }}"
    state: "present"
    display_name: "Дом"
    internationalization_enabled: false
    registration_allowed: false
    remember_me: true
    enabled: true

- name: "Create client"
  community.general.keycloak_client:
    auth_keycloak_url: "{{ keycloak_auth_url }}"
    auth_realm: "master"
    auth_username: "{{ keycloak_admin_name }}"
    auth_password: "{{ keycloak_admin_password }}"
    name: "Home client"
    client_id: "{{ keycloak_client_id }}"
    enabled: true
    protocol: "openid-connect"
    realm: "{{ keycloak_realm }}"
    standard_flow_enabled: true
    state: "present"
    root_url: "http://keycloak.home/"
    redirect_uris:
      - "http://wiki.home/*"
    web_origins:
      - "+"
    public_client: false
    client_authenticator_type: "client-secret"
    secret: "{{ keycloak_realm_secret }}"


- name: "Create users"
  community.general.keycloak_user:
    auth_keycloak_url: "{{ keycloak_auth_url }}"
    auth_realm: "master"
    auth_username: "{{ keycloak_admin_name }}"
    auth_password: "{{ keycloak_admin_password }}"
    realm: "{{ keycloak_realm }}"
    username: "{{ item.username }}"
    enabled: true
    email_verified: true
    first_name: "{{ item.firstName }}"
    last_name: "{{ item.lastName }}"
    email: "{{ item.email }}"
    credentials:
      - type: "password"
        value: "{{ item.password }}"
        temporary: false
    state: "present"
  no_log: true
  with_items: "{{ keycloak_users }}"
