---
- name: "Setup master node"
  hosts: "master"
  vars_files:
    - "vars/main.yml"
    - "vars/{{ env }}.yml"
  roles:
    - role: "coredns"
      coredns_version: "1.10.1"

    - role: "k3s"
      k3s_version: "v1.26.3+k3s1"

    - role: "longhorn"
      longhorn_version: "1.4.1"

    - role: "postgresql"
      postgresql_version: "12.3.1"
      postgresql_namespace: "{{ prod_namespace }}"
      postgresql_admin_password: "{{ postgresql.root_password }}"
      postgresql_volume_size: "{{ postgresql.volume_size }}"

    - role: "wikijs"
      wikijs_version: "2.2.20"
      wikijs_namespace: "{{ prod_namespace }}"
