---
- name: "Setup master node"
  hosts: "master"
  vars_files:
    - "vars/{{ env }}.yml"
  roles:
    - role: "stepca"
      stepca_version: "0.23.2"
      stepca_cli_version: "0.23.4"
      stepca_root_password: "{{ stepca.root_password }}"
      stepca_name: "Home"
      stepca_dns: "127.0.0.1,home"
      stepca_address: ":9000"
      stepca_provisioner: "dshemin@home"

    - role: "etcd"
      etcd_version: "3.5.7"

    - role: "coredns"
      coredns_version: "1.10.1"
