---
- name: "Setup master node"
  hosts: "master"
  vars_files:
    - "vars/{{ env }}.yml"
  roles:
    - role: "coredns"
      coredns_version: "1.10.1"

    - role: "k3s"
      k3s_version: "v1.26.3+k3s1"

    - role: "longhorn"
      longhorn_version: "1.4.1"
