---
- name: "Check target OS"
  ansible.builtin.fail:
    msg: "Only AlmaLinux is supported, current system is {{ ansible_facts.system }}"
  when: 'ansible_facts.distribution != "AlmaLinux"'

- name: "Install iSCSI"
  ansible.builtin.dnf:
    name:
      - "iscsi-initiator-utils"
    state: "present"

- name: "Create Longhorn namespace"
  kubernetes.core.k8s:
    name: "{{ longhorn_namespace }}"
    api_version: "v1"
    kind: "Namespace"
    state: "present"

- name: "Create Helm CRD for Longhorn"
  kubernetes.core.k8s:
    template: "longhorn.j2"
    state: "present"
