---
- name: "Create pgAdmin namespace"
  kubernetes.core.k8s:
    name: "{{ pgadmin_namespace }}"
    api_version: "v1"
    kind: "Namespace"
    state: "present"

- name: "Create secret for pgAdmin"
  kubernetes.core.k8s:
    template: "secret.j2"
    state: "present"

- name: "Create Helm CRD for pgAdmin"
  kubernetes.core.k8s:
    template: "helm.j2"
    state: "present"
