---
stepca_version: "{{ undef(hint='You must specify SmallStep step-ca binary version') }}"
stepca_root_password: "{{ undef(hint='You must specify SmallStep step-ca CA key password') }}"
stepca_cli_version: "{{ undef(hint='You must specify SmallStep step CLI version') }}"

stepca_user: "stepca"
stepca_group: "{{ stepca_user }}"

stepca_executable: "/usr/sbin/step-ca"
stepca_home_dir: "/home/{{ stepca_user }}"
stepca_root_password_file: "{{ stepca_home_dir }}/password"
stepca_config_file: "{{ stepca_home_dir }}/config/ca.json"

stepca_download_baseurl: "https://github.com/smallstep/certificates/releases/download/v{{ stepca_version }}"
stepca_archive_name: "step-ca_linux_{{ stepca_version }}_{{ stepca_arch[ansible_architecture] }}.tar.gz"
stepca_download_url: "{{ stepca_download_baseurl }}/{{ stepca_archive_name }}"

stepca_service_name: "step-ca.service"
stepca_service_file: "/etc/systemd/system/{{ stepca_service_name }}"

stepca_cli_executable: "/usr/sbin/step"

stepca_cli_download_baseurl: "https://github.com/smallstep/cli/releases/download/v{{ stepca_cli_version }}"
stepca_cli_archive_name: "step_linux_{{ stepca_cli_version }}_{{ stepca_arch[ansible_architecture] }}.tar.gz"
stepca_cli_download_url: "{{ stepca_cli_download_baseurl }}/{{ stepca_cli_archive_name }}"

stepca_arch:
  x86_64: "amd64"
  aarch64: "arm64"
