---
- name: "Create user {{ stepca_user }}"
  ansible.builtin.user:
    name: "{{ stepca_user }}"
    group: "{{ stepca_group }}"
    password: "!"
    home: "{{ stepca_home_dir }}"
    shell: "/sbin/nologin"
    comment: "SmallStep user"
    system: true
    state: "present"

- name: "Create home directory {{ stepca_home_dir }}"
  ansible.builtin.file:
    name: "{{ stepca_home_dir }}"
    owner: "{{ stepca_user }}"
    group: "{{ stepca_group }}"
    mode: 0700
    state: "directory"

- name: "Put password file to {{ stepca_root_password_file }}"
  ansible.builtin.copy:
    content: "{{ stepca_root_password }}"
    dest: "{{ stepca_root_password_file }}"
    owner: "{{ stepca_user }}"
    group: "{{ stepca_group }}"
    mode: 0600
