---
- name: "Look for existing install"
  ansible.builtin.stat:
    path: "{{ stepca_config_file }}"
  register: stepca_config_present

- name: "Initialize CA"
  when: not stepca_config_present.stat.exists
  block:
    - name: "Initialize CA"
      ansible.builtin.command: >-
        {{ stepca_cli_executable }} ca init
        --deployment-type=standalone
        --name={{ stepca_name | quote }}
        --dns={{ stepca_dns | quote }}
        --address={{ stepca_address | quote }}
        --provisioner={{ stepca_provisioner | quote }}
        --password-file={{ stepca_root_password_file | quote }}
        --provisioner-password-file={{ stepca_root_password_file | quote }}
        --acme
        --remote-management
      environment:
        STEPPATH: "{{ stepca_home_dir }}"
      become: true
      become_user: "{{ stepca_user }}"

- name: "Systemd unit file is present"
  ansible.builtin.template:
    src: "step-ca.service.j2"
    dest: "{{ stepca_service_file }}"
    owner: "root"
    group: "root"
    mode: 0644

- name: "Service is enabled and running"
  ansible.builtin.systemd:
    name: "{{ stepca_service_name }}"
    state: "started"
    enabled: true
