---
- name: "Put configuration"
  ansible.builtin.template:
    src: "Corefile.j2"
    dest: "{{ coredns_config_file }}"
    owner: "{{ coredns_user }}"
    group: "{{ coredns_group }}"
    mode: 0600
  notify: "Restart coredns"

- name: "Systemd unit file is present"
  ansible.builtin.template:
    src: "coredns.service.j2"
    dest: "{{ coredns_service_file }}"
    owner: "root"
    group: "root"
    mode: 0644

- name: "Service is enabled and running"
  ansible.builtin.systemd:
    name: "{{ coredns_service_name }}"
    state: "started"
    enabled: true
    daemon_reload: true
