---
etcd_version: "{{ undef(hint='You must specify etcd version') }}"

etcd_executable: "/usr/sbin/etcd"
etcdctl_executable: "/usr/sbin/etcdctl"
etcdutl_executable: "/usr/sbin/etcdutl"
etcd_home_dir: "/opt/etcd"
etcd_certs_dir: "{{ etcd_home_dir }}/certs"
etcd_data_dir: "{{ etcd_home_dir }}/data"
etcd_ca_root_file: "{{ etcd_certs_dir }}/root_ca.crt"
etcd_csr_file: "{{ etcd_certs_dir }}/csr"
etcd_cert_file: "{{ etcd_certs_dir }}/cert"
etcd_key_file: "{{ etcd_certs_dir }}/key"

etcd_download_baseurl: "https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}"
etcd_archive_name: "etcd-v{{ etcd_version }}-linux-{{ stepca_arch[ansible_architecture] }}.tar.gz"
etcd_tmp_dir: "/tmp/{{ etcd_archive_name | splitext | first | splitext | first }}"
etcd_download_url: "{{ etcd_download_baseurl }}/{{ etcd_archive_name }}"

etcd_service_name: "etcd.service"
etcd_service_file: "/etc/systemd/system/{{ etcd_service_name }}"

etcd_arch:
  x86_64: "amd64"
  aarch64: "arm64"
