---
- name: "Check target OS"
  ansible.builtin.fail:
    msg: "Only AlmaLinux is supported, current system is {{ ansible_facts.system }}"
  when: 'ansible_facts.distribution != "AlmaLinux"'

- name: "Add repository {{ docker_repository_url }}"
  ansible.builtin.command:
    cmd: "dnf config-manager --add-repo {{ docker_repository_url }}"
    creates: "{{ docker_repository_path }}"

- name: "Remove conflicted packages"
  ansible.builtin.dnf:
    name:
      - "podman"
      - "buildah"
    state: "absent"

- name: "Install packages"
  ansible.builtin.dnf:
    name:
      - "docker-ce"
      - "docker-ce-cli"
      - "containerd.io"
      - "pip"
    state: "present"

- name: "Install required provisioning dependencies"
  ansible.builtin.pip:
    name:
      - "requests"
    state: "present"

- name: "Enable and start docker"
  ansible.builtin.service:
    name: "docker"
    state: "started"
    enabled: "yes"
